# Generated by Django 4.1 on 2022-11-30 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                ("id_adm", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50)),
                ("telefono", models.BigIntegerField()),
                ("correo", models.CharField(max_length=50)),
                ("provincia", models.CharField(max_length=50)),
                ("usuario", models.CharField(max_length=20)),
                ("contrasenia", models.CharField(max_length=20)),
            ],
            options={"db_table": "administrador", "managed": False,},
        ),
        migrations.CreateModel(
            name="Bodega",
            fields=[
                (
                    "id_bodega",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("comuna", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50)),
            ],
            options={"db_table": "bodega", "managed": False,},
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id_categoria",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=50)),
            ],
            options={"db_table": "categoria", "managed": False,},
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "rut_cli",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50)),
                ("telefono", models.BigIntegerField()),
                ("correo", models.CharField(max_length=50)),
                ("usuario", models.CharField(max_length=20)),
                ("contrasenia", models.CharField(max_length=20)),
                ("id_cliente", models.BigIntegerField()),
            ],
            options={"db_table": "cliente", "managed": False,},
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id_comuna",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("comuna", models.CharField(max_length=64)),
            ],
            options={"db_table": "comuna", "managed": False,},
        ),
        migrations.CreateModel(
            name="Consultor",
            fields=[
                (
                    "id_consultor",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("apellido", models.CharField(max_length=20)),
                ("telefono", models.BigIntegerField()),
                ("direccion", models.CharField(max_length=50)),
                ("usuario", models.CharField(max_length=20)),
                ("contrasenia", models.CharField(max_length=20)),
            ],
            options={"db_table": "consultor", "managed": False,},
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id_contrato",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("vigencia", models.CharField(max_length=1)),
                ("observaciones", models.CharField(max_length=255)),
            ],
            options={"db_table": "contrato", "managed": False,},
        ),
        migrations.CreateModel(
            name="ContratoTransporte",
            fields=[
                (
                    "id_contrato",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("vigencia", models.CharField(max_length=1)),
            ],
            options={"db_table": "contrato_transporte", "managed": False,},
        ),
        migrations.CreateModel(
            name="EstadoProducto",
            fields=[
                (
                    "id_estado",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=50)),
            ],
            options={"db_table": "estado_producto", "managed": False,},
        ),
        migrations.CreateModel(
            name="EstadoSubasta",
            fields=[
                (
                    "id_estado",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=64)),
            ],
            options={"db_table": "estado_subasta", "managed": False,},
        ),
        migrations.CreateModel(
            name="LicenciaConducir",
            fields=[
                (
                    "id_licencia",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={"db_table": "licencia_conducir", "managed": False,},
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                ("id_orden", models.BigIntegerField(primary_key=True, serialize=False)),
                ("detalles", models.CharField(max_length=50)),
                ("cantidad", models.BigIntegerField()),
            ],
            options={"db_table": "orden_compra", "managed": False,},
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id_pago", models.BigIntegerField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=50)),
                ("id_pedido", models.BigIntegerField()),
            ],
            options={"db_table": "pago", "managed": False,},
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id_pais", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={"db_table": "pais", "managed": False,},
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id_pedido",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("fecha_ingreso", models.DateField()),
                ("fecha_envio", models.DateField()),
                ("sub_total", models.BigIntegerField(blank=True, null=True)),
                ("p_transporte", models.BigIntegerField(blank=True, null=True)),
                ("comision_mg", models.BigIntegerField(blank=True, null=True)),
                ("total_pagar", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "pedido", "managed": False,},
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id_producto",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre_producto", models.CharField(max_length=50)),
            ],
            options={"db_table": "producto", "managed": False,},
        ),
        migrations.CreateModel(
            name="Productor",
            fields=[
                (
                    "rut_pro",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellido_pat", models.CharField(max_length=50)),
                ("apellido_mat", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=70)),
                ("telefono", models.BigIntegerField()),
                ("correo", models.CharField(max_length=200)),
                ("fecha_creacion", models.DateField()),
                ("usuario", models.CharField(max_length=20)),
                ("contrasenia", models.CharField(max_length=20)),
                ("id_productor", models.BigIntegerField()),
            ],
            options={"db_table": "productor", "managed": False,},
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "provincia_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("provincia", models.CharField(max_length=64)),
            ],
            options={"db_table": "provincia", "managed": False,},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "region_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("region", models.CharField(max_length=64)),
                ("abreviatura", models.CharField(max_length=64)),
                ("capital", models.CharField(max_length=64)),
            ],
            options={"db_table": "region", "managed": False,},
        ),
        migrations.CreateModel(
            name="Seguro",
            fields=[
                (
                    "id_seguro",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("empresa", models.CharField(max_length=50)),
                ("detalles", models.CharField(max_length=50)),
            ],
            options={"db_table": "seguro", "managed": False,},
        ),
        migrations.CreateModel(
            name="Subasta",
            fields=[
                (
                    "id_subasta",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("fecha_ingreso", models.DateField()),
                ("fecha_termino", models.DateField()),
            ],
            options={"db_table": "subasta", "managed": False,},
        ),
        migrations.CreateModel(
            name="TipoCliente",
            fields=[
                (
                    "id_tipocliente",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=20)),
            ],
            options={"db_table": "tipo_cliente", "managed": False,},
        ),
        migrations.CreateModel(
            name="Transporte",
            fields=[
                (
                    "id_transporte",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("tamano", models.CharField(max_length=50)),
                ("refrigeracion", models.CharField(max_length=50)),
                ("capacidad_carga", models.CharField(max_length=50)),
                ("patente", models.CharField(max_length=8)),
            ],
            options={"db_table": "transporte", "managed": False,},
        ),
        migrations.CreateModel(
            name="Transportista",
            fields=[
                (
                    "id_transportista",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("telefono", models.BigIntegerField()),
                ("usuario", models.CharField(max_length=20)),
                ("contrasenia", models.CharField(max_length=20)),
                ("correo", models.CharField(max_length=80)),
            ],
            options={"db_table": "transportista", "managed": False,},
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("usuario", models.CharField(max_length=20)),
                ("contrasenia", models.CharField(blank=True, max_length=20, null=True)),
                ("tipo_usuario", models.CharField(max_length=20)),
            ],
            options={"db_table": "usuario", "managed": False,},
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id_pedido",
                    models.OneToOneField(
                        db_column="id_pedido",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="webinar.pedido",
                    ),
                ),
                ("cantidad", models.BigIntegerField()),
                ("valor", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "detalle_pedido", "managed": False,},
        ),
        migrations.CreateModel(
            name="Puja",
            fields=[
                (
                    "id_subasta",
                    models.OneToOneField(
                        db_column="id_subasta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="webinar.subasta",
                    ),
                ),
                ("valor", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "puja", "managed": False,},
        ),
        migrations.CreateModel(
            name="RegistroProducto",
            fields=[
                (
                    "rut_pro",
                    models.OneToOneField(
                        db_column="rut_pro",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="webinar.productor",
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("cantidad_kg", models.BigIntegerField(blank=True, null=True)),
                ("precio_kg", models.BigIntegerField(blank=True, null=True)),
                ("cantidad_unidad", models.BigIntegerField(blank=True, null=True)),
                ("precio_unidad", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "registro_producto", "managed": False,},
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                ("id_reporte", models.BigIntegerField()),
                ("descripcion", models.CharField(max_length=80)),
                ("estado", models.CharField(max_length=50)),
                (
                    "id_consultor",
                    models.OneToOneField(
                        db_column="id_consultor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="webinar.consultor",
                    ),
                ),
            ],
            options={"db_table": "reporte", "managed": False,},
        ),
    ]
